version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: treasury_timescaledb
    environment:
      POSTGRES_DB: treasury_dashboard
      POSTGRES_USER: treasury_user
      POSTGRES_PASSWORD: treasury_pass_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c shared_preload_libraries=timescaledb

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    container_name: treasury_backend
    environment:
      DATABASE_URL: postgresql://treasury_user:treasury_pass_2024@timescaledb:5432/treasury_dashboard
      COINGECKO_API_KEY: ${COINGECKO_API_KEY}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb
    volumes:
      - ../backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
    container_name: treasury_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  timescale_data: